### PR TITLE
Add more documentation

### LINKED ISSUE #41: Add documentation
We should document things that are specific to our network, e.g., how to construct proper intents for different kinds of transactions.

### PR DESCRIPTION
**Pull request by abukosek**
Closes #41.

### CODE REVIEW

**Comment by kostko** [comment]
Can you fix CI to also run for `*.md` changes (they are currently excluded, preventing required checks to complete).

**Comment by abukosek** [comment]
This looks like a bug in GitHub Actions -- it should use the state of the branch that this branch is based on, as there are no code changes.
The workflow ignores `*.md` files on purpose, so we don't rebuild and retest everything for non-code changes.
If we don't want that, I can change it to run the checks for every change, but that seems dumb.

**Comment by kostko** [comment]
How is that a bug? You can only specify that certain CI statuses must be successful before a PR can be merged. Those status checks must run otherwise there will be no status report and as such required checks will not be completed.

You need to do this differently -- if there are only Markdown modifications, skip code tests. But don't skip the jobs themselves.

**Comment by abukosek** [comment]
The GitHub Actions syntax doesn't seem to support doing what you are suggesting easily, so I will remove the `*.md` filter.
IMO, it would make more sense for the workflow to use previous state if it's skipped, rather than having to implement manual comparisons in each job, but it's a new service, so I guess they'll add support for doing this in a nicer way at some point.

**Review by kostko — APPROVED** [review]

**Pull request merged**
